#!/usr/bin/env python3
"""Dump every playable costume's karma options to a markdown reference.

Used so the user can scan the full per-costume / per-slot option matrix
without scrolling through the costume editor in the browser. Run from the
project root or invoke with no args; output goes to KARMA_REFERENCE.md.

The user asked for this so they can give precise per-costume preferences
in future chats — "for costume X slot Y, pick effect Z" — rather than
deriving them from a global wishlist that doesn't always match a costume's
specific odds pool.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from web import config  # noqa: E402
from web.services import karma_service  # noqa: E402


def main() -> None:
    output_path = ROOT / "KARMA_REFERENCE.md"
    catalog_path = ROOT / "data" / "names" / "playable_costumes.json"
    if not catalog_path.exists():
        sys.exit(f"missing {catalog_path}; run {config.SETUP_SCRIPT} to extract names")

    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    costumes = [r for r in catalog.get("records", []) if int(r.get("RarityType", 0) or 0) == 40]
    costumes.sort(key=lambda r: (str(r.get("character_name", "")), str(r.get("name", ""))))

    pools = karma_service.get_pools()
    slot_groups = karma_service.get_costume_slot_groups()

    lines: list[str] = []
    lines.append("# Karma options — per-costume reference")
    lines.append("")
    lines.append(
        f"Generated by `tools/dump_karma_options.py`. Lists every R40 (4-star) "
        f"playable costume in the game and the karma options available in each "
        f"of its 3 slots. Use this when telling Claude which effect to pick on "
        f"a specific costume.")
    lines.append("")
    lines.append(f"**Total costumes**: {len(costumes)}")
    lines.append("")
    lines.append("Each option is listed as `[Rarity] OddsNumber=N | EffectType:TargetId | Label`.")
    lines.append(
        "The OddsNumber is the value lunar-tear writes to "
        "`user_costume_lottery_effects.odds_number` when the slot is rolled to "
        "that effect.")
    lines.append("")
    lines.append("---")
    lines.append("")

    for rec in costumes:
        cid = int(rec["id"])
        name = rec.get("name", "")
        char = rec.get("character_name", "")
        lines.append(f"## {name} ({char}) — id {cid}")
        slot_to_gid = slot_groups.get(cid)
        if not slot_to_gid:
            lines.append("")
            lines.append("> No karma slot data (costume has no lottery effect entries).")
            lines.append("")
            continue
        for slot in (1, 2, 3):
            gid = slot_to_gid.get(slot)
            if gid is None:
                lines.append(f"### Slot {slot}: (no group)")
                lines.append("")
                continue
            pool = pools.get(gid, [])
            lines.append(f"### Slot {slot} (group {gid})")
            lines.append("")
            for entry in pool:
                lines.append(
                    f"- [R{entry.rarity}] OddsNumber={entry.odds_number} | "
                    f"{entry.effect_type}:{entry.target_id} | {entry.label}"
                )
            lines.append("")
        lines.append("---")
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {output_path} ({len(costumes)} costumes)")


if __name__ == "__main__":
    main()
